### ISSUE TITLE
ERROR: 500 INTERNAL SERVER ERROR    on web page when i try submit demo text

### ISSUE THREAD

**Issue by Researcher-123** [dmis-lab/BERN2#25]
ERROR: 500 INTERNAL SERVER ERROR    on web page when i try submit demo text

The problem I encountered when installing BERN2 (maybe the cause of the failure is not this):
       Latest Pythorch support only CUDA 11.3 , but I can in install only CUDA 11.5 driver on RTX3050 

Hardware: laptop ASUS TUF GAMING F17 FX706HCB     (CPU i5, 32Gb RAM, RTX3050 4Gb)
Software:  Ubuntu 22.04 , Python 3.8

Terminal:

`bash run_bern2.sh
Arguments:
	host: 0.0.0.0
	port: 8888
	mtner_home: ./multi_ner
	mtner_port: 18894
	gnormplus_home: ./resources/GNormPlusJava
	gnormplus_port: 18895
	tmvar2_home: ./resources/tmVarJava
	tmvar2_port: 18896
	cache_host: localhost
	cache_port: 27017
	gene_norm_port: 18888
	disease_norm_port: 18892
	use_neural_normalizer: True
	keep_files: False
	front_dev: False
/home/john/miniconda3/envs/bern2_conda_py3.8/BERN2/app
[11/May/2022 21:26:35.972463] BERN2 LOADING..
./output 0
./resources/GNormPlusJava/input 0
./resources/tmVarJava/input 0
start loading neural normalizer..
Downloading: 100%|██████████| 401/401 [00:00<00:00, 495kB/s]
Downloading: 100%|██████████| 226k/226k [00:02<00:00, 78.6kB/s] 
Downloading: 100%|██████████| 461k/461k [00:01<00:00, 411kB/s]  
Downloading: 100%|██████████| 112/112 [00:00<00:00, 149kB/s]
Downloading: 100%|██████████| 686/686 [00:00<00:00, 1.06MB/s]
Downloading: 100%|██████████| 438M/438M [09:21<00:00, 779kB/s]     
neural_disease_normalizer is loaded.. model=dmis-lab/biosyn-sapbert-bc5cdr-disease , dictionary=resources/normalization/normalizers/neural_norm_caches/dict_Disease_20210630.txt.pk
Downloading: 100%|██████████| 401/401 [00:00<00:00, 604kB/s]
Downloading: 100%|██████████| 226k/226k [00:08<00:00, 27.8kB/s] 
Downloading: 100%|██████████| 461k/461k [00:07<00:00, 63.0kB/s] 
Downloading: 100%|██████████| 112/112 [00:00<00:00, 152kB/s]
Downloading: 100%|██████████| 686/686 [00:00<00:00, 1.14MB/s]
Downloading: 100%|██████████| 438M/438M [09:26<00:00, 773kB/s]  
neural_chemical_normalizer is loaded.. model=dmis-lab/biosyn-sapbert-bc5cdr-chemical , dictionary=resources/normalization/normalizers/neural_norm_caches/dict_ChemicalCompound_20210630.txt.pk
Downloading: 100%|██████████| 401/401 [00:00<00:00, 571kB/s]
Downloading: 100%|██████████| 226k/226k [00:02<00:00, 96.0kB/s] 
Downloading: 100%|██████████| 461k/461k [00:16<00:00, 28.3kB/s] 
Downloading: 100%|██████████| 112/112 [00:00<00:00, 156kB/s]
Downloading: 100%|██████████| 686/686 [00:00<00:00, 1.02MB/s]
Downloading: 100%|██████████| 438M/438M [04:20<00:00, 1.68MB/s] 
neural_gene_normalizer is loaded.. model=dmis-lab/biosyn-sapbert-bc2gn , dictionary=resources/normalization/normalizers/neural_norm_caches/dict_Gene.txt.pk
[11/May/2022 21:52:00.387454] BERN2 LOADED..
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:8888
 * Running on http://192.168.0.101:8888 (Press CTRL+C to quit)
127.0.0.1 - - [11/May/2022 21:52:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/May/2022 21:52:12] "GET /static/css/sb-admin-2.min.css HTTP/1.1" 200 -
127.0.0.1 - - [11/May/2022 21:52:12] "GET /static/css/default.css HTTP/1.1" 200 -
127.0.0.1 - - [11/May/2022 21:52:12] "GET /static/css/index.css HTTP/1.1" 200 -
127.0.0.1 - - [11/May/2022 21:52:12] "GET /static/css/tooltip.css HTTP/1.1" 200 -
127.0.0.1 - - [11/May/2022 21:52:12] "GET /static/css/loader.css HTTP/1.1" 200 -
127.0.0.1 - - [11/May/2022 21:52:12] "GET /static/js/jquery.min.js HTTP/1.1" 200 -
127.0.0.1 - - [11/May/2022 21:52:12] "GET /static/js/jquery.easing.min.js HTTP/1.1" 200 -
127.0.0.1 - - [11/May/2022 21:52:12] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 -
127.0.0.1 - - [11/May/2022 21:52:12] "GET /static/js/sb-admin-2.min.js HTTP/1.1" 200 -
127.0.0.1 - - [11/May/2022 21:52:12] "GET /static/js/main.js HTTP/1.1" 200 -
127.0.0.1 - - [11/May/2022 21:52:21] "GET /static/images/favicon.ico HTTP/1.1" 200 -
[11/May/2022 21:52:24.269196] id: 0ad2e7ad31c876c70cbbe308d5327975eee82a857a29544d0c0080d5
[Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/BERN2/bern2/bern2.py", line 106, in annotate_text
    output = self.tag_entities(text, base_name)
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/BERN2/bern2/bern2.py", line 358, in tag_entities
    async_result = loop.run_until_complete(self.async_ner(arguments_for_coroutines))
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/BERN2/bern2/bern2.py", line 491, in async_ner
    result = await asyncio.gather(*coroutines)
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/BERN2/bern2/bern2.py", line 533, in _ner_wrap
    with open(output_mtner, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './multi_ner/output/0ad2e7ad31c876c70cbbe308d5327975eee82a857a29544d0c0080d5.PubTator.json'

[2022-05-11 21:52:24,273] ERROR in app: Exception on /senddata [POST]
Traceback (most recent call last):
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/BERN2/app/__init__.py", line 117, in send_data
    _code, parse_res, keys_in_dict = r_parser.parse_result(result_dict, draw_keys, result_id="text")
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/BERN2/app/result_parser.py", line 210, in parse_result
    org_text = result_dict['text']
KeyError: 'text'
127.0.0.1 - - [11/May/2022 21:52:24] "POST /senddata HTTP/1.1" 500 -
192.168.0.101 - - [11/May/2022 21:54:45] "GET / HTTP/1.1" 200 -
192.168.0.101 - - [11/May/2022 21:54:45] "GET /static/css/default.css HTTP/1.1" 200 -
192.168.0.101 - - [11/May/2022 21:54:45] "GET /static/css/sb-admin-2.min.css HTTP/1.1" 200 -
192.168.0.101 - - [11/May/2022 21:54:45] "GET /static/css/loader.css HTTP/1.1" 200 -
192.168.0.101 - - [11/May/2022 21:54:45] "GET /static/css/index.css HTTP/1.1" 200 -
192.168.0.101 - - [11/May/2022 21:54:45] "GET /static/css/tooltip.css HTTP/1.1" 200 -
192.168.0.101 - - [11/May/2022 21:54:45] "GET /static/js/jquery.min.js HTTP/1.1" 200 -
192.168.0.101 - - [11/May/2022 21:54:45] "GET /static/js/sb-admin-2.min.js HTTP/1.1" 200 -
192.168.0.101 - - [11/May/2022 21:54:45] "GET /static/js/jquery.easing.min.js HTTP/1.1" 200 -
192.168.0.101 - - [11/May/2022 21:54:45] "GET /static/js/bootstrap.bundle.min.js HTTP/1.1" 200 -
192.168.0.101 - - [11/May/2022 21:54:45] "GET /static/js/main.js HTTP/1.1" 200 -
192.168.0.101 - - [11/May/2022 21:54:47] "GET /static/images/favicon.ico HTTP/1.1" 200 -
[11/May/2022 21:54:52.597321] id: f667f75e25b0cb68d93240dc7a503986a7876e5b3c3d2e491611a88c
[Errno 111] Connection refused
[11/May/2022 21:54:52.598551] [f667f75e25b0cb68d93240dc7a503986a7876e5b3c3d2e491611a88c] GNormPlus 0.00019931793212890625 sec
[11/May/2022 21:54:52.685996] [f667f75e25b0cb68d93240dc7a503986a7876e5b3c3d2e491611a88c] tmVar 2.0 0.08804559707641602 sec
[11/May/2022 21:54:54.179709] [f667f75e25b0cb68d93240dc7a503986a7876e5b3c3d2e491611a88c] Multi-task NER 1.581083059310913 sec, #entities: 11
Traceback (most recent call last):
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: './resources/GNormPlusJava/output/f667f75e25b0cb68d93240dc7a503986a7876e5b3c3d2e491611a88c.PubTator' -> './resources/tmVarJava/input/f667f75e25b0cb68d93240dc7a503986a7876e5b3c3d2e491611a88c.PubTator.PubTator.Gene'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/BERN2/bern2/bern2.py", line 106, in annotate_text
    output = self.tag_entities(text, base_name)
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/BERN2/bern2/bern2.py", line 371, in tag_entities
    shutil.move(output_gnormplus, input_tmvar_gene)
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: './resources/GNormPlusJava/output/f667f75e25b0cb68d93240dc7a503986a7876e5b3c3d2e491611a88c.PubTator'

[2022-05-11 21:54:54,180] ERROR in app: Exception on /senddata [POST]
Traceback (most recent call last):
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/BERN2/app/__init__.py", line 117, in send_data
    _code, parse_res, keys_in_dict = r_parser.parse_result(result_dict, draw_keys, result_id="text")
  File "/home/john/miniconda3/envs/bern2_conda_py3.8/BERN2/app/result_parser.py", line 210, in parse_result
    org_text = result_dict['text']
KeyError: 'text'
192.168.0.101 - - [11/May/2022 21:54:54] "POST /senddata HTTP/1.1" 500 -
`

**Comment by mjeensung** [comment]
Hi @Researcher-123 

Thanks for reporting the issue.

It's most likely that the external modules (Multi-NER, tmVar, GNormPlus, etc.) are causing the issue. The reasons are various, so we need to check the logs.

The log files are saved in `/logs` so you can check them to see which module is causing the issue.

If you find anything suspicious in the logs, please share it with me so that I can help you.

**Comment by mjeensung** [comment]
We uploaded a new version of the resource files.
Here's how to download the resource and install it.
Could you try this?

```
wget http://nlp.dmis.korea.edu/projects/bern2-sung-et-al-2022/resources_v1.1.b.tar.gz
tar -zxvf resources_v1.1.b.tar.gz
rm -rf resources_v1.1.b.tar.gz

# (For Linux/MacOS Users) install CRF 
cd resources/GNormPlusJava
tar -zxvf CRF++-0.58.tar.gz
mv CRF++-0.58 CRF
cd CRF
./configure --prefix="$HOME"
make
make install
cd ../../..

# (For Windows Users) install CRF 
cd resources/GNormPlusJava
unzip -zxvf CRF++-0.58.zip
mv CRF++-0.58 CRF
cd ../..
```

**Comment by Researcher-123** [comment]
Thanks for your reply. Unfortunately, I'm unlikely to ever return to your project since I have already done a lot of work to create my own NER.
