### ISSUE TITLE
Found no NVIDIA driver for CPU (run_bern2_cpu.sh)

### ISSUE THREAD

**Issue by anopperl** [dmis-lab/BERN2#61]
CPU : bern2

- Hello all and @mjeensung , I am trying to run run_bern2_cpu.sh. I have checked logs  "nohup_multi_ner.out" file and it is saying that "Found no NVIDIA driver". I thing, for CPU user there no need to have NVIDIA driver. right ?
- sorry for my English

Logs: "nohup_multi_ner.out" 

Traceback (most recent call last):
  File "/bern2local/multi_ner/ner_server.py", line 89, in <module>
    mt_ner = MTNER(args)
  File "/bern2local/multi_ner/main.py", line 521, in __init__
    self.model = self.model.cuda()
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 911, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 911, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/inde
x.aspx

**Comment by mjeensung** [comment]
Hi @anopperl 

Thank you for reporting the issue!
We have resolved it, so could you please update the code and run BERN2 again?
(see https://github.com/dmis-lab/BERN2/commit/3bb255c7ff3e02e9c1c2cdd44caed13c2afe1518)

**Comment by anopperl** [comment]
Hi @mjeensung  thanks.  there is no error in "nohup_multi_ner.out" but now errors are in  nohup_bern2.out


[27/Mar/2024 06:51:44.937765] id: 93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab
[27/Mar/2024 06:51:45.448458] [93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] tmVar 2.0 0.5086250305175781 sec
[27/Mar/2024 06:51:45.804228] [93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] GNormPlus 0.8629016876220703 sec
[27/Mar/2024 06:51:48.531194] [93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] Multi-task NER 3.589254856109619 sec, #entities: 64
[27/Mar/2024 06:51:51.088236] [93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] ALL NER 6.149087190628052 sec
ent_type = diseaseent_type = drug
[27/Mar/2024 06:51:51.089104] [93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] [drug] 0.000 sec, CUI-less: 7.7% (1/13)

ent_type = geneent_type = speciesent_type = cell_line

[27/Mar/2024 06:51:51.089867] [93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] [species] 0.000 sec, CUI-less: 0.0% (0/2)

[27/Mar/2024 06:51:51.090215]ent_type = DNA 
ent_type = cell_typeWARN! DNA is not supported yet
[27/Mar/2024 06:51:51.090808][93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] [cell_line] 0.001 sec, CUI-less: 100.0% (4/4)

[27/Mar/2024 06:51:51.090951] [93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] [DNA] 0.000 sec, CUI-less: 100.0% (6/6)
 [93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] [cell_type] 0.000 sec, CUI-less: 100.0% (5/5)
[27/Mar/2024 06:51:51.291597] [93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] [disease] 0.203 sec, CUI-less: 31.2% (5/16)
[27/Mar/2024 06:51:51.333462] [93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] [gene] 0.244 sec, CUI-less: 22.2% (4/18)
[27/Mar/2024 06:51:51.333631] [93ef66feb48de91c1a58a22f1d8afae0bbd27996720e1bb02f5ca1ab] Rule-based normalization 0.245 sec (1 article(s), 7 entity type(s))
# cui-less in disease=5
Traceback (most recent call last):
  File "/bern2local/bern2/bern2.py", line 107, in annotate_text
    output = self.tag_entities(text, base_name)
  File "/bern2local/bern2/bern2.py", line 403, in tag_entities
    tagged_docs = self.normalizer.neural_normalize(
  File "/bern2local/bern2/normalizer.py", line 195, in neural_normalize
    norm_entities = self.neural_disease_normalizer.normalize(
  File "/bern2local/normalizers/neural_normalizer.py", line 85, in normalize
    for batch in name_dataloader:
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/bern2local/normalizers/neural_normalizer.py", line 25, in __getitem__
    return {key: torch.tensor(val[idx]).cuda() for key, val in self.encodings.items()} if not self.no_cuda else \
  File "/bern2local/normalizers/neural_normalizer.py", line 25, in <dictcomp>
    return {key: torch.tensor(val[idx]).cuda() for key, val in self.encodings.items()} if not self.no_cuda else \
  File "/usr/local/envs/bern2/lib/python3.9/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by mjeensung** [comment]
My bad, we've found another missing part that controls the usage of CUDA.
We have resolved it, so could you please update the code and run BERN2 again?

(see https://github.com/dmis-lab/BERN2/commit/b508e01fd6b1afff8d017110b5e653d800e2c802)
